#!/bin/bash
# idirname stands for interactive dirname.

# If only one argumen is given...
if
	[ $(echo "$@" | wc -l) -eq 1 ]
	then
		# If it's a directory, leave the argument unchanged and redirect it to stdout.
		if
			[ -d "$@" ]
			then echo "$@"
		fi

		# If it's a file, get the directory that contains it and redirect that to stdout.
		if
			[ -f "$@" ]
			then echo "$(dirname "$@")"
		fi	

	else
		echo "idirname takes only one argument."
fi

